### ISSUE TITLE
Faster Sexp#line options

### ISSUE THREAD

**Issue by presidentbeef** [seattlerb/sexp_processor#30]
Right now, `Sexp#line` can be used to either fetch or set the line number. This has led to some bugs which were addressed by https://github.com/seattlerb/sexp_processor/commit/ce284487f057203360c41b14d2b25f8c5453fbb9

But `Sexp#line` is quite a bit slower (relatively) due to the added logic. The method gets called a lot, so it _might_ make sense to have a faster path.

<details>
  <summary>Benchmark code</summary>

```ruby
require 'sexp_processor'
require 'benchmark/ips'

class Sexp
  def set_line x
    @line = x
    self
  end

  def get_line
    @line
  end
end

test_sexp = Sexp.new.line(1)

Benchmark.ips do |x|
  x.report "line" do
    test_sexp.line(10)
  end

  x.report "set_line" do
    test_sexp.set_line(10)
  end

  x.report "line=" do
    test_sexp.line = 10
  end

  x.compare!
end

Benchmark.ips do |x|
  x.report "line" do
    test_sexp.line
  end

  x.report "get_line" do
    test_sexp.get_line
  end

  x.compare!
end
```
</details>

<details>
  <summary>Benchmark results</summary>

```
Warming up --------------------------------------
                line    88.816k i/100ms
            set_line   176.887k i/100ms
               line=   193.423k i/100ms
Calculating -------------------------------------
                line      1.708M (± 3.0%) i/s -      8.615M in   5.047446s
            set_line      6.326M (± 4.3%) i/s -     31.663M in   5.014701s
               line=      7.188M (± 3.2%) i/s -     35.977M in   5.010991s

Comparison:
               line=:  7187710.6 i/s
            set_line:  6326318.9 i/s - 1.14x  slower
                line:  1708412.4 i/s - 4.21x  slower

Warming up --------------------------------------
                line   145.990k i/100ms
            get_line   197.802k i/100ms
Calculating -------------------------------------
                line      3.323M (± 3.3%) i/s -     16.643M in   5.014754s
            get_line      8.896M (± 4.2%) i/s -     44.505M in   5.012103s

Comparison:
            get_line:  8896218.1 i/s
                line:  3322652.5 i/s - 2.68x  slower
```
</details>

I did a rough search-and-replace of calls to `Sexp#line` in SexpProcessor and RubyParser. The performance difference is _maybe_ 3-5%. So maybe not worth it?

The method names could certainly use work. I like `Sexp#with_line` to suggest that it is returning `self`. `Sexp#lineno` or `Sexp#line_no` could be used for fetching? Since lines are often copied from existing `Sexp`s, maybe a method like `Sexp#copy_line` to pass in a `Sexp`?

Just thoughts, not attached to any of this.

**Comment by zenspider** [comment]
The logic causes some slowdown, but a bigger chunk than I thought was happening because of that stupid `n != UNASSIGNED`, surprisingly... It's a plain object, so I expected it to be object identity comparison only. Not only was I wrong, but `==` is more costly than `!=` these days???

So, `line3` is the same as the current version, with the logic inverted to only use `==` for roughly an 11% boost. And `line2` switches from `==` to `.equal?` for a 126%(!!) boost above that.

I will certainly do the latter... I'm not sure about adding `get_` and `set_`... that's awfully clunky. I kinda want to revamp the whole library tbh.

```
Comparison:
               line=: 14376054.6 i/s
            set_line: 13954309.9 i/s - same-ish: difference falls within error
               line2:  8292654.0 i/s - 1.73x  slower # use equal?
               line3:  3681193.9 i/s - 3.91x  slower # cost of not: switching != to == ?!?!
                line:  3309975.9 i/s - 4.34x  slower # current
```

**Comment by zenspider** [comment]
```
Comparison:
               line=: 14512618.8 i/s
            set_line: 13018852.3 i/s - 1.11x  slower
          line_equal:  8181429.4 i/s - 1.77x  slower
            line_eq2:  3764150.4 i/s - 3.86x  slower
        line_current:  3473887.8 i/s - 4.18x  slower
```

**Comment by zenspider** [comment]
This is so fucking strange... using `equal?` is SLOWER for the getter case?!?! I have no fucking idea what's going on.

**Comment by presidentbeef** [comment]
I wonder if `Nil#equal?` vs. `Object#equal?` makes any difference?? So wild.

I mean, it's pretty fast as-is, this is really micro-optimizing, but I do find Brakeman spends a considerable amount of time setting line numbers if I use a sampling profiler.

**Comment by zenspider** [comment]
My how machines and ruby versions have changed...
```
Comparison:
            line_eq2: 10859680.5 i/s
           line_neq2: 10844208.1 i/s - same-ish: difference falls within error
         line_equal2: 10798477.8 i/s - 1.01x  (± 0.00) slower
          line_equal: 10667866.7 i/s - 1.02x  (± 0.00) slower
           orig_line: 10623854.1 i/s - 1.02x  (± 0.00) slower
            line_neq: 10608638.2 i/s - 1.02x  (± 0.00) slower

Comparison (UNASSIGNED frozen):
            line_eq2: 11025878.0 i/s
           line_neq2: 11020092.2 i/s - same-ish: difference falls within error
           orig_line: 10865724.2 i/s - 1.01x  (± 0.00) slower
            line_neq: 10795490.9 i/s - same-ish: difference falls within error
         line_equal2: 10355374.7 i/s - 1.06x  (± 0.00) slower
          line_equal: 10187097.6 i/s - 1.08x  (± 0.00) slower
```
